"""Connector readiness is separate from per-device control capability."""

PROVIDERS = [
    {
        "id": "Deye",
        "implemented": True,
        "regions": ["eu", "am", "india"],
        "fields": ["app_id", "app_secret", "identity_value", "password"],
        "identity": True,
        "discovery": "plants_devices",
        "read": "native_points",
        "write": "commissioning_required",
        "evidence": ["DEYE_API_001"],
        "url": "https://developer.deyecloud.com/",
    },
    {
        "id": "Solis",
        "implemented": True,
        "regions": ["global"],
        "fields": ["key_id", "key_secret"],
        "identity": False,
        "discovery": "plants_inverters",
        "read": "native_points",
        "write": "register_profile_required",
        "evidence": ["SOLIS_DEV_DATA_002", "SOLIS_DEV_AUTH_002"],
        "url": "https://developer.soliscloud.com/guide/data-access-user.html",
    },
    {
        "id": "SOLARMAN",
        "implemented": True,
        "regions": ["global", "cn"],
        "fields": ["app_id", "app_secret", "identity_value", "password"],
        "identity": True,
        "discovery": "plants_devices",
        "read": "native_points",
        "write": "oem_profile_required",
        "evidence": ["SOLARMAN_CLOUD_002"],
        "url": "https://doc.solarmanpv.com/en/Documentation%20and%20Quick%20Guide",
    },
    {
        "id": "GoodWe",
        "implemented": True,
        "regions": ["global", "eu", "au"],
        "fields": ["account", "password", "plant_ids"],
        "setup_help": {
            "vi": "Nhập tài khoản SEMS và tối đa 100 ID nhà máy không trùng, phân cách bằng dấu phẩy. Chỉ chọn nhà máy tài khoản được phép truy cập; cấu hình này không tự khám phá mọi nhà máy. Không dùng mật khẩu cục bộ Solar Fleet. Lưu chưa xác nhận kết nối hoặc quyền điều khiển.",
            "en": "Enter SEMS credentials and up to 100 distinct comma-separated plant IDs. Select only plants accessible to this account; this configuration does not automatically discover every plant. Do not use your local Solar Fleet password. Saving does not verify connectivity or authorize control.",
        },
        "identity": False,
        "discovery": "plants_devices",
        "read": "native_points",
        "write": "commissioning_required",
        "evidence": ["GOODWE_API_001"],
        "url": "https://www.semsportal.com/",
    },
    {
        "id": "Sungrow",
        "implemented": True,
        "regions": ["global"],
        "fields": ["app_key", "app_secret", "user_account", "user_password", "plant_ids", "point_ids"],
        "setup_help": {
            "vi": "Nhập thông tin ứng dụng và tài khoản iSolarCloud, tối đa 100 ID nhà máy không trùng và tối đa 200 ID điểm đo dạng số, phân cách bằng dấu phẩy. Chọn ID theo hợp đồng tài khoản/model; không suy ra điểm đo từ tên hãng. Không dùng mật khẩu cục bộ Solar Fleet. Lưu chưa xác nhận kết nối hoặc quyền điều khiển.",
            "en": "Enter iSolarCloud application and account credentials, up to 100 distinct plant IDs and up to 200 numeric point IDs, comma-separated. Select IDs from the account/model contract; do not infer points from the brand. Do not use your local Solar Fleet password. Saving does not verify connectivity or authorize control.",
        },
        "identity": False,
        "discovery": "plants_devices",
        "read": "native_points",
        "write": "commissioning_required",
        "evidence": ["SUNGROW_OM_001"],
        "url": "https://developer-api.isolarcloud.com/",
    },
    {
        "id": "Huawei",
        "implemented": True,
        "regions": ["global", "eu", "cn"],
        "fields": ["user_name", "system_code"],
        "identity": False,
        "discovery": "plants_devices",
        "read": "native_points",
        "write": "commissioning_required",
        "evidence": ["HUAWEI_AUTH_001"],
        "url": "https://intl.fusionsolar.huawei.com/",
    },
    {
        "id": "Growatt",
        "implemented": True,
        "regions": ["global", "server"],
        "fields": ["token"],
        "identity": False,
        "discovery": "plants_devices",
        "read": "native_points",
        "write": "commissioning_required",
        "evidence": ["GROWATT_OSS_001"],
        "url": "https://openapi.growatt.com/",
    },
    {
        "id": "Eybond / SmartESS",
        "implemented": True,
        "regions": ["dessmonitor", "shinemonitor"],
        "region_label": {"vi": "Nền tảng tài khoản", "en": "Account platform"},
        "region_names": {
            "dessmonitor": "DessMonitor / SmartESS",
            "shinemonitor": "ShineMonitor / SmartClient for Solar",
        },
        "fields": ["user_name", "password", "company_key"],
        "account_identity_field": "user_name",
        "field_labels": {
            "user_name": {"vi": "Tài khoản hãng", "en": "Vendor username"},
            "company_key": {"vi": "Company key do nền tảng cấp", "en": "Platform company key"},
        },
        "secret_fields": ["password", "company_key"],
        "field_defaults": {"company_key": "bnrl_frRFjEz8Mkn"},
        "setup_help": {
            "vi": "Chọn đúng nền tảng đang chứa thiết bị. Nhập tài khoản hãng và company key của nền tảng/đơn vị cài đặt. Không tự chuyển sang host khác khi đăng nhập lỗi. Thu thập tối thiểu 5 phút; thời gian đo và thông số chuẩn hóa cần đối chiếu theo model.",
            "en": "Choose the platform that contains your devices. Enter its account and the company key supplied by the platform/installer. A failed login will not switch hosts. Collection is at least every 5 minutes; source time and canonical metrics need model-specific verification.",
        },
        "minimum_poll_seconds": 300,
        "identity": False,
        "discovery": "plants_collectors_devices",
        "read": "native_points",
        "write": "commissioning_required",
        "evidence": ["EYBOND_DESSMONITOR_AUDIT_001", "EYBOND_GUIDE_001"],
        "url": "https://www.eybond.com/",
    },
    {
        "id": "Bluesun",
        "implemented": False,
        "regions": ["local"],
        "fields": ["logger_serial", "model_family"],
        "identity": False,
        "discovery": "exact_platform_profile_required",
        "read": "native_points",
        "write": "commissioning_required",
        "evidence": ["BLUESUN_BSM_001", "BLUESUN_COMMUNITY_002", "SOLARMAN_OSS_002"],
        "url": "https://www.bluesunpv.com/",
    },
]


def provider(id):
    return next((p for p in PROVIDERS if p["id"] == id), None)
