from typing import Any, Protocol

from ..domain import Ack, Configuration, Device, OrderResult, VendorCall


class ControlAdapter(Protocol):
    async def configuration(self, device: Device) -> Configuration: ...
    async def send(self, call: VendorCall) -> Ack: ...
    async def order(self, order_id: str) -> OrderResult: ...
    async def history(self, *args: Any, **kwargs: Any) -> Any: ...
    async def alerts(self, *args: Any, **kwargs: Any) -> Any: ...
