from typing import Any, Callable, Protocol

from ..domain import Ack, Configuration, Device, OrderResult, VendorCall


class ControlAdapter(Protocol):
    async def configuration(self, device: Device, *args: Any, **kwargs: Any) -> Configuration: ...
    async def send(self, call: VendorCall, *, before_send: Callable[[], None]) -> Ack: ...
    async def order(self, order_id: str) -> OrderResult: ...
    async def history(self, *args: Any, **kwargs: Any) -> Any: ...
    async def alerts(self, *args: Any, **kwargs: Any) -> Any: ...
